### PR TITLE
Create python-app.yml

### PR DESCRIPTION
**Pull request by siddhant3030**

### CODE REVIEW

**Comment by fatchat** [comment]
@Abhishek-N will assist @siddhant3030 on this
with the goal of automating the tests current in DDP_backend/scripts/*.py

**Comment by fatchat** [comment]
@siddhant3030 what's the update on this issue?

**Comment by siddhant3030** [comment]
> @siddhant3030 what's the update on this issue?

@fatchat You have to provide some public domain. I don't have much experience in that.

**Comment by fatchat** [comment]
> > @siddhant3030 what's the update on this issue?
> 
> @fatchat You have to provide some public domain. I don't have much experience in that.

Oh you mean an Airbyte which GitHub can connect to?

Yeah let's park that for a little while, can we get a code coverage report by running some command(s) locally? Is that already set up, if so please point me towards the documentation I have not been running any of the pytests

**Comment by fatchat** [comment]
@Abhishek-N you can take over this ticket, connect to airbyte via ssh and run the tests

**Pull request closed without merging**
