### PR TITLE
14 encrypt credentials to target warehouse before storing in database

### PR DESCRIPTION
**Pull request by Ishankoradia**
Keeping this open. We can merge this when we finalize on the encyprtion tool we will use.

Right now we are using kms encryption using a single key for all organizations

### CODE REVIEW

**Review by fatchat — COMMENTED** [review]
this is nice, but a couple comments:
- when going between bytes and strings you should use encode() and decode() with a codec like utf8
- if an aws api call fails (or any api call for that matter), if you're not going to pass the error message down the call stack you should at least log it

**Comment by Ishankoradia** [comment]
> this is nice, but a couple comments:
> 
> * when going between bytes and strings you should use encode() and decode() with a codec like utf8
> * if an aws api call fails (or any api call for that matter), if you're not going to pass the error message down the call stack you should at least log it

Got it. I have made the changes accordingly.

**Review by fatchat — APPROVED** [review]
won't merge at this time

**Comment by fatchat** [comment]
this will be covered by PR #52

**Pull request closed without merging**
